---
 title: "Pregunta 2 del capítulo 7."
---

Let $X_1, \dots , X_n \sim Bernoulli(p)$ and let $Y_1, \dots , Y_m \sim Bernoulli(q)$. Find the plug-in estimator and estimated standard error for $p$. Find an approximate 90 percent conﬁdence interval for $p$. Find the plug-in estimator and estimated standard error for $p − q$. Find an approximate 90 percent conﬁdence interval for $p − q$.


1) Find the plug-in estimator and estimated standard error for $p$.


Solución: 

Para encontrar el estimador plug-in hay que notar que $\mathbb{E}(X) = p$. Y de acuerdo con lo que vimos en clase el operador $\mathbb{E}$ es lineal. Así:

\[\widehat{p}_{plug-in} = \overline{X}\]


2) Find an approximate 90 percent conﬁdence interval for $p$.


Como $\mathbb{E}(X), Var(X) < \infty$ se puede aplicar el teorema del límite central:

\[\frac{\overline{X} - p}{\sqrt{\frac{p(1-p)}{n}}} \to N(0,1)\]

Así el intervalo para muestras grandes al $90\%$ es de la forma:

\[(\overline{X} - Z_{0.05}*\sqrt{\frac{\overline{X}(1-\overline{X})}{n}},  \overline{X} + Z_{0.95}*\sqrt{\frac{\overline{X}(1-\overline{X})}{n}})\]

Donde $Z_{0.95} = -Z_{0.05} \thickapprox 1.644854$.


3) Find the plug-in estimator and estimated standard error for $p − q$.


Propondemos la siguiente transformación: $W = \overline{X} - \overline{Y}$.


Mostraremos que $\mathbb{E}(W) = p - q$. 


\[\mathbb{E}(W) = \mathbb{E}(\overline{X}) - \mathbb{E}(\overline{Y}) = p - q.\]

Así el estimador plug-in es 

\[\widehat{p-q}_{plug-in} = W\]

4) Find an approximate 90 percent conﬁdence interval for $p − q$.

Usaremos una aproximación asintotica por el teorema del límite central. 

Primero necesitamos verificar que la varianza de $Z$ es finita.

\[Var(W) = Var(\overline{X}-\overline{Y}) \overset{ind}{=} Var(\overline{X}) + Var(\overline{Y}) = \frac{p(1-p)}{n} + \frac{q(1-q)}{n}.\]


Así $Var(W) = \frac{p(1-p)}{n} + \frac{q(1-q)}{n}$ por lo que $W \overset{n \to \infty}{\sim} N(p-q,\frac{p(1-p)}{n} + \frac{q(1-q)}{n})$.

Entonces el intervalo de confianza al $90\%$ utilizando estimadores plug-in es de la forma:

\[(w - Z_{0.05}*\sqrt{\frac{S^2_W}{n}},  W + Z_{0.95}*\sqrt{\frac{S^2_W}{n}})\]

Donde $S^2_W = \overline{X}(1-\overline{X}) + \overline{Y}(1-\overline{Y})$.



